name: Eco-CI v1.24.04
run-name: On push old release
on:
  push:
    branches:
      - feature/eco-ci-v1.24.04

permissions:
  read-all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Start Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4 # use hash or @vX here (See note below)
        with:
          task: start-measurement
        # continue-on-error: true # recommended setting for production. See notes below.


      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          repository: supabase/supabase
          ref: feature/eco-ci-v1.24.04
          sparse-checkout: |
            packages
            
      - name: Checkout Repo Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4 # use hash or @vX here (See note below)
        with:
          task: get-measurement
          label: 'repo checkout'
        # continue-on-error: true # recommended setting for production. See notes below.

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential python3 g++ make

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
        
      - name: Install deps
        run: npm ci

      - name: Setup Python Measurment
        uses: green-coding-solutions/eco-ci-energy-estimation@v4 # use hash or @vX here (See note below)
        with:
          task: get-measurement
          label: 'python setup'
        continue-on-error: true # recommended setting for production. See notes below.

      - name: Run tests
        run: npm run test:ui

      - name: Tests measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4 # use hash or @vX here (See note below)
        with:
          task: get-measurement
          label: 'pytest'
        continue-on-error: true # recommended setting for production. See notes below.

      - name: Show Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4 # use hash or @vX here (See note below)
        with:
          task: display-results
        continue-on-error: true # recommended setting for production. See notes below.
